Add `isclose` guard to `standard_deviation`
Otherwise, a `seq` of identical values can result in::

    File "_TFL/Math_Func.py", line 293, in standard_deviation
      return sqrt ((a1 - a2) / (n * (n - 1)))
  ValueError: math domain error

due to `a1 - a2` computing as a very small negative value
like `-1.2126596023639042e-12`.