Rename `MOM.inspect` to `MOM.Inspect`
After a upgrade of setuptools to 34.3.0, _MOM/setup.py failed with the
traceback::

  Traceback (most recent call last):
    File "_MOM/setup.py", line 28, in <module>
      from   setuptools               import setup
    File "/PVE/std/lib/python2.7/site-packages/setuptools/__init__.py", line 13, in <module>
      from setuptools.extension import Extension
    File "/PVE/std/lib/python2.7/site-packages/setuptools/extension.py", line 29, in <module>
      _Extension = get_unpatched(distutils.core.Extension)
    File "/PVE/std/lib/python2.7/site-packages/setuptools/monkey.py", line 30, in get_unpatched
      return lookup(item)
    File "/PVE/std/lib/python2.7/site-packages/setuptools/monkey.py", line 41, in get_unpatched_class
      for cls in inspect.getmro(cls)
  AttributeError: 'module' object has no attribute 'getmro'

Renaming the module MOM.inspect to MOM.Inspect solves the problem.

Bad monkey, setuptools, bad monkey!!!