Wrap `safe_str_cmp` to normalize args
Encode both arguments as iso-8859-1 strings

To avoid this exception triggered by Python 2.7.8 in combination with
werkzeug 0.9.4::

  File "/usr/lib64/python2.7/site-packages/werkzeug/security.py",
      line 117, in safe_str_cmp
    return _builtin_safe_str_cmp(a, b)
  TypeError: 'unicode' does not have the buffer interface